name: CI
on: push

jobs:
  publish:
    name: Publish to npm
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Set up Node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - name: Publish to npm
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: npm publish --access public
