name: CI
on: push

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        node-version: [ 12.x ]
        os: [ linux-latest, macos-latest, windows-latest ]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Install dependencies
        if: matrix.os == "linux-latest"
        run: |
          apt-get -qq update
          apt-get install -y opencl-headers ocl-icd-opencl-dev
          # Install OpenCL (CPU) runtime
          # https://software.intel.com/en-us/articles/opencl-drivers#latest_CPU_runtime
          PACKAGE_URL=http://registrationcenter-download.intel.com/akdlm/irc_nas/12556/opencl_runtime_16.1.2_x64_rh_6.4.0.37.tgz
          PACKAGE_NAME=opencl_runtime_16.1.2_x64_rh_6.4.0.37
          wget -q ${PACKAGE_URL} -O /tmp/opencl_runtime.tgz
          tar -xzf /tmp/opencl_runtime.tgz -C /tmp
          sed 's/decline/accept/g' -i /tmp/${PACKAGE_NAME}/silent.cfg
          /tmp/${PACKAGE_NAME}/install.sh -s /tmp/${PACKAGE_NAME}/silent.cfg
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install
        run: yarn install

  publish:
    name: Publish to npm
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Set up Node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
          registry-url: 'https://registry.npmjs.org'
      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: npm publish
